openapi: 3.0.0
info:
  title: Complex Type Graphs API
  version: 1.0.0
  description: API for testing complex type reference graphs

paths:
  /api/companies:
    post:
      summary: Register a new company with complex organizational structure
      operationId: registerCompany
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyRegistrationRequest'
      responses:
        '200':
          description: Company registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyRegistrationResponse'

components:
  schemas:
    Address:
      type: object
      required:
        - street
        - city
        - country
      properties:
        street:
          type: string
        city:
          type: string
        country:
          type: string

    Contact:
      type: object
      required:
        - email
        - phone
        - address
      properties:
        email:
          type: string
          format: email
        phone:
          type: string
        address:
          $ref: '#/components/schemas/Address'

    Department:
      type: object
      required:
        - id
        - name
        - manager
      properties:
        id:
          type: string
        name:
          type: string
        manager:
          $ref: '#/components/schemas/Employee'

    Employee:
      type: object
      required:
        - id
        - name
        - contact
        - department
        - reportsTo
      properties:
        id:
          type: string
        name:
          type: string
        contact:
          $ref: '#/components/schemas/Contact'
        department:
          $ref: '#/components/schemas/Department'
        reportsTo:
          $ref: '#/components/schemas/Employee'

    Company:
      type: object
      required:
        - id
        - name
        - address
        - ceo
        - departments
      properties:
        id:
          type: string
        name:
          type: string
        address:
          $ref: '#/components/schemas/Address'
        ceo:
          $ref: '#/components/schemas/Employee'
        departments:
          $ref: '#/components/schemas/Department'

    CompanyRegistrationRequest:
      type: object
      required:
        - company
      properties:
        company:
          $ref: '#/components/schemas/Company'

    CompanyRegistrationResponse:
      type: object
      required:
        - companyId
        - registrationNumber
      properties:
        companyId:
          type: string
        registrationNumber:
          type: string
