openapi: 3.0.0
info:
  title: Bank Transfer API
  version: 1.0.0
  description: API for executing bank transfers with regulatory compliance

paths:
  /api/transfers:
    post:
      summary: Execute a bank transfer between accounts
      operationId: executeBankTransfer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BankTransferRequest'
      responses:
        '200':
          description: Transfer executed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BankTransferResponse'

components:
  schemas:
    BankTransferRequest:
      type: object
      required:
        - customer
        - transfer
        - confirmAmount
      properties:
        customer:
          $ref: '#/components/schemas/Customer'
        transfer:
          $ref: '#/components/schemas/TransferRequest'
        confirmAmount:
          type: number
          format: decimal

    BankTransferResponse:
      type: object
      required:
        - transferId
        - status
        - fee
        - executionDate
      properties:
        transferId:
          type: string
        status:
          type: string
          enum: [PENDING, EXECUTED, FAILED]
        fee:
          $ref: '#/components/schemas/Money'
        executionDate:
          type: string
          format: date

    Customer:
      type: object
      required:
        - id
        - name
        - email
        - age
        - country
        - registrationDate
      properties:
        id:
          type: string
        name:
          type: string
          minLength: 2
          maxLength: 100
        email:
          type: string
          format: email
        age:
          type: integer
          minimum: 18
          maximum: 120
        country:
          type: string
          enum: [FR, DE, IT, ES, UK]
        registrationDate:
          type: string
          format: date

    TransferRequest:
      type: object
      required:
        - fromAccount
        - toAccount
        - amount
        - description
        - executionDate
      properties:
        fromAccount:
          type: string
        toAccount:
          type: string
        amount:
          $ref: '#/components/schemas/Money'
        description:
          type: string
          maxLength: 140
        executionDate:
          type: string
          format: date

    Money:
      type: object
      required:
        - amount
        - currency
      properties:
        amount:
          type: number
          format: decimal
          minimum: 0
          maximum: 50000
        currency:
          type: string
          enum: [EUR]
