openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
  description: API for testing intent type signature validation

paths:
  /api/auth/login:
    post:
      summary: Authenticate user with credentials
      operationId: authenticateUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'

  /api/auth/logout:
    post:
      summary: Log out authenticated user
      operationId: logoutUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutRequest'
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogoutResponse'

components:
  schemas:
    UserCredentials:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          minLength: 3
        password:
          type: string
          minLength: 8

    UserProfile:
      type: object
      required:
        - id
        - username
        - email
        - createdAt
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
          format: email
        createdAt:
          type: string
          format: date-time

    LoginRequest:
      type: object
      required:
        - credentials
        - rememberMe
      properties:
        credentials:
          $ref: '#/components/schemas/UserCredentials'
        rememberMe:
          type: boolean

    LoginResponse:
      type: object
      required:
        - success
        - user
        - token
        - expiresAt
      properties:
        success:
          type: boolean
        user:
          $ref: '#/components/schemas/UserProfile'
        token:
          type: string
        expiresAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      required:
        - errorCode
        - message
        - timestamp
      properties:
        errorCode:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time

    LogoutRequest:
      type: object
      required:
        - token
        - userId
      properties:
        token:
          type: string
        userId:
          type: string

    LogoutResponse:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
